name: "Trigger CircleCI Pipeline"
description: "Trigger pipelines on CircleCI for any event on GitHub."
branding:
  icon: "check-circle"
  color: "green"
runs:
  using: "node12"
  main: "dist/index.js"
